// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOmu5AI7v0mAnH-APgD7vGO5GSUrmotI0',
    appId: '1:374864587492:web:c35051ad4320cf23a91af1',
    messagingSenderId: '374864587492',
    projectId: 'notes-dev-flutter',
    authDomain: 'notes-dev-flutter.firebaseapp.com',
    storageBucket: 'notes-dev-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7y8YiYH2g2SZUgUDaRfTRHyoPMfDIlo',
    appId: '1:374864587492:android:9031bea7d780b032a91af1',
    messagingSenderId: '374864587492',
    projectId: 'notes-dev-flutter',
    storageBucket: 'notes-dev-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQSJUxpa0sk5zjIS3XUiRFt6xNWxDnL4',
    appId: '1:374864587492:ios:c21cb544c44afa90a91af1',
    messagingSenderId: '374864587492',
    projectId: 'notes-dev-flutter',
    storageBucket: 'notes-dev-flutter.appspot.com',
    iosBundleId: 'com.development.myNotes',
  );
}
